// <auto-generated />
using System;
using HRMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HRMS.Infrastructure.Data.Migrations.Master
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20251119100114_AddPasswordExpiresAtToEmployeeAndAdminUser")]
    partial class AddPasswordExpiresAtToEmployeeAndAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("master")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HRMS.Core.Entities.Master.ActivationResendLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Parsed device info (Mobile/Desktop, browser, OS)");

                    b.Property<bool>("EmailDelivered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Was activation email delivered successfully?");

                    b.Property<string>("EmailSendError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("SMTP error or bounce reason if delivery failed");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Failure reason if Success=false (rate limit, email error, validation failure, etc.)");

                    b.Property<string>("Geolocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("City, country for fraud detection");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When resend was requested (UTC) - used for sliding window rate limits");

                    b.Property<string>("RequestedByEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Email address used in request (must match tenant email)");

                    b.Property<string>("RequestedFromIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasComment("IP address of requester (IPv4 or IPv6) for security monitoring");

                    b.Property<int>("ResendCountLastHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of resend attempts in last hour (real-time rate limit tracking)");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Was resend successful? (false if rate limited or email send failed)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasComment("Tenant ID (enables per-tenant rate limiting)");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Token expiration timestamp (UTC) - typically 24 hours from RequestedAt");

                    b.Property<string>("TokenGenerated")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasComment("New token generated (truncated for security - never full token!)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("User agent string for fraud detection");

                    b.Property<bool>("WasRateLimited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Was this request blocked by rate limiting?");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_ActivationResendLogs_RequestedAt");

                    b.HasIndex("RequestedFromIp")
                        .HasDatabaseName("IX_ActivationResendLogs_RequestedFromIp");

                    b.HasIndex("Success")
                        .HasDatabaseName("IX_ActivationResendLogs_Success");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ActivationResendLogs_TenantId");

                    b.HasIndex("RequestedFromIp", "RequestedAt")
                        .HasDatabaseName("IX_ActivationResendLogs_IP_RequestedAt");

                    b.HasIndex("TenantId", "RequestedAt")
                        .HasDatabaseName("IX_ActivationResendLogs_TenantId_RequestedAt");

                    b.ToTable("ActivationResendLogs", "master", t =>
                        {
                            t.HasComment("Fortune 500 activation resend audit log for multi-tenant SaaS. Enables rate limiting (max 3 per hour), security monitoring, and GDPR compliance. IMMUTABLE logs with cascade delete on tenant deletion.");
                        });
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActivationTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AllowedIPAddresses")
                        .HasColumnType("text");

                    b.Property<string>("AllowedLoginHours")
                        .HasColumnType("text");

                    b.Property<string>("BackupCodes")
                        .HasColumnType("jsonb")
                        .HasComment("JSON array of SHA256-hashed backup codes for MFA recovery");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBySuperAdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInitialSetupAccount")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFailedLoginAttempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginIPAddress")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedBySuperAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PasswordExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHistory")
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("StatusNotes")
                        .HasColumnType("text");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AdminUsers", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasComment("Standardized action type (enum stored as integer)");

                    b.Property<string>("AdditionalMetadata")
                        .HasColumnType("jsonb")
                        .HasComment("Additional metadata in JSON format (flexible for future extensions)");

                    b.Property<string>("ApprovalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Approval reference if action required approval");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Archival date (when moved to cold storage)");

                    b.Property<DateTime?>("BusinessDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Business date for payroll/leave actions");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasComment("High-level category for filtering (enum stored as integer)");

                    b.Property<string>("ChangedFields")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Comma-separated list of changed field names");

                    b.Property<string>("Checksum")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("SHA256 checksum for tamper detection");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Correlation ID for distributed tracing");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Parsed device information (mobile, desktop, tablet, OS, browser)");

                    b.Property<string>("DocumentationLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Link to related documentation or policy");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasComment("Action duration in milliseconds (for performance tracking)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasComment("Entity ID affected (if applicable)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Entity type affected (Employee, LeaveRequest, Payroll, etc.)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Error message if action failed");

                    b.Property<string>("Geolocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Geolocation information (city, country, coordinates)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("HTTP method (GET, POST, PUT, DELETE)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasComment("IP address of the user (IPv4 or IPv6)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Flag indicating if entry has been archived to cold storage");

                    b.Property<bool>("IsUnderLegalHold")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LegalHoldId")
                        .HasColumnType("uuid");

                    b.Property<string>("NetworkInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Network information (ISP, organization)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasComment("New values after change (JSON format)");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasComment("Old values before change (JSON format)");

                    b.Property<Guid?>("ParentActionId")
                        .HasColumnType("uuid")
                        .HasComment("Parent action ID for multi-step operations");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Timestamp when action was performed (UTC)");

                    b.Property<string>("PolicyReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Policy reference that triggered this action");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Query string parameters");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("User-provided reason for the action");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Request path/endpoint");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("integer")
                        .HasComment("HTTP response status code");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Session ID for tracking related actions");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasComment("Severity level for alerting (enum stored as integer)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasComment("Whether the action succeeded");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasComment("Tenant ID (null for SuperAdmin platform-level actions)");

                    b.Property<string>("TenantName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Denormalized tenant name for reporting");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("User agent string (browser/device information)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User email address");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("User full name for audit trail readability");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("User ID who performed the action");

                    b.Property<string>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("User role at time of action (SuperAdmin, TenantAdmin, HR, Manager, Employee)");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("IX_AuditLogs_ActionType");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_AuditLogs_Category");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLogs_CorrelationId");

                    b.HasIndex("PerformedAt")
                        .HasDatabaseName("IX_AuditLogs_PerformedAt");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_AuditLogs_SessionId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_AuditLogs_Severity");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AuditLogs_TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.HasIndex("Category", "PerformedAt")
                        .HasDatabaseName("IX_AuditLogs_Category_PerformedAt");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.HasIndex("IsArchived", "PerformedAt")
                        .HasDatabaseName("IX_AuditLogs_IsArchived_PerformedAt");

                    b.HasIndex("Success", "PerformedAt")
                        .HasDatabaseName("IX_AuditLogs_Success_PerformedAt");

                    b.HasIndex("TenantId", "PerformedAt")
                        .HasDatabaseName("IX_AuditLogs_TenantId_PerformedAt");

                    b.HasIndex("UserId", "PerformedAt")
                        .HasDatabaseName("IX_AuditLogs_UserId_PerformedAt");

                    b.HasIndex("TenantId", "Category", "PerformedAt")
                        .HasDatabaseName("IX_AuditLogs_TenantId_Category_PerformedAt");

                    b.ToTable("AuditLogs", "master", t =>
                        {
                            t.HasComment("Production-grade audit log with 10+ year retention. IMMUTABLE - no UPDATE/DELETE allowed (enforced by DB triggers). Partitioned by PerformedAt (monthly). Meets Mauritius compliance requirements.");
                        });
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.DetectedAnomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnomalyType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectionRule")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("InvestigatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvestigatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("InvestigationNotes")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("text");

                    b.Property<string>("NotificationRecipients")
                        .HasColumnType("text");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RelatedAuditLogIds")
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnomalyType");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("Status", "DetectedAt");

                    b.HasIndex("TenantId", "DetectedAt");

                    b.ToTable("DetectedAnomalies", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AreaSqKm")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DistrictNameFrench")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("DistrictCode")
                        .IsUnique();

                    b.HasIndex("Region");

                    b.ToTable("Districts", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Feature description for documentation");

                    b.Property<DateTime?>("EmergencyDisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Emergency rollback timestamp");

                    b.Property<string>("EmergencyDisabledBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("SuperAdmin who triggered emergency rollback");

                    b.Property<string>("EmergencyDisabledReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Reason for emergency rollback (audit trail)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmergencyDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Emergency rollback flag for quick disable");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether feature is enabled (default FALSE for safety)");

                    b.Property<string>("MinimumTier")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Minimum tier required (NULL = all tiers)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Module name (auth, dashboard, employees, payroll, etc.)");

                    b.Property<int>("RolloutPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Rollout percentage 0-100 (0=disabled, 100=fully enabled)");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Tags for categorization (comma-separated)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasComment("Tenant ID (NULL = global default, NON-NULL = tenant override)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsEmergencyDisabled")
                        .HasDatabaseName("IX_FeatureFlags_IsEmergencyDisabled");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_FeatureFlags_IsEnabled");

                    b.HasIndex("Module")
                        .HasDatabaseName("IX_FeatureFlags_Module");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FeatureFlags_TenantId");

                    b.HasIndex("TenantId", "Module")
                        .IsUnique()
                        .HasDatabaseName("IX_FeatureFlags_TenantId_Module");

                    b.ToTable("FeatureFlags", "master", t =>
                        {
                            t.HasComment("Fortune 500 feature flag system for per-tenant control. Enables canary deployment, gradual rollout, emergency rollback, A/B testing. NULL TenantId = global default, NON-NULL = tenant override.");
                        });
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.IndustrySector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentSectorId")
                        .HasColumnType("integer");

                    b.Property<string>("RemunerationOrderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RemunerationOrderYear")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresSpecialPermits")
                        .HasColumnType("boolean");

                    b.Property<string>("SectorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SectorNameFrench")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentSectorId");

                    b.HasIndex("SectorCode")
                        .IsUnique();

                    b.ToTable("IndustrySectors", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.LegalHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalMetadata")
                        .HasColumnType("text");

                    b.Property<int>("AffectedAuditLogCount")
                        .HasColumnType("integer");

                    b.Property<int>("AffectedEntityCount")
                        .HasColumnType("integer");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ComplianceFrameworks")
                        .HasColumnType("text");

                    b.Property<string>("CourtOrder")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityTypes")
                        .HasColumnType("jsonb");

                    b.Property<string>("LawFirm")
                        .HasColumnType("text");

                    b.Property<string>("LegalRepresentative")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LegalRepresentativeEmail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotifiedUsers")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReleasedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedBy")
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<int?>("RetentionPeriodDays")
                        .HasColumnType("integer");

                    b.Property<string>("SearchKeywords")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("UserIds")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("LegalHolds", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.PostalCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VillageId")
                        .HasColumnType("integer");

                    b.Property<string>("VillageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DistrictId");

                    b.HasIndex("VillageId");

                    b.HasIndex("VillageName", "DistrictName");

                    b.ToTable("PostalCodes", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("AdminUserId", "ExpiresAt");

                    b.ToTable("RefreshTokens", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.SectorComplianceRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalReference")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RuleCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RuleConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RuleCategory");

                    b.HasIndex("SectorId");

                    b.HasIndex("EffectiveFrom", "EffectiveTo");

                    b.ToTable("SectorComplianceRules", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.SecurityAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When alert was acknowledged (UTC)");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uuid")
                        .HasComment("User ID who acknowledged the alert");

                    b.Property<string>("AcknowledgedByEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Email of user who acknowledged");

                    b.Property<string>("AdditionalMetadata")
                        .HasColumnType("jsonb")
                        .HasComment("Additional metadata (JSON)");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer")
                        .HasComment("Type of security alert (enum stored as integer)");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasComment("Assigned to user ID");

                    b.Property<string>("AssignedToEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Assigned to user email");

                    b.Property<int?>("AuditActionType")
                        .HasColumnType("integer")
                        .HasComment("Related audit log action type");

                    b.Property<Guid?>("AuditLogId")
                        .HasColumnType("uuid")
                        .HasComment("Related audit log entry ID");

                    b.Property<string>("BaselineMetrics")
                        .HasColumnType("jsonb")
                        .HasComment("Baseline metrics (JSON)");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasComment("Alert category for classification");

                    b.Property<string>("ComplianceFrameworks")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Related compliance frameworks");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Correlation ID for distributed tracing");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When alert was created (UTC)");

                    b.Property<string>("CurrentMetrics")
                        .HasColumnType("jsonb")
                        .HasComment("Current metrics that triggered alert (JSON)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When alert was soft-deleted");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Detailed alert description");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When alert was first detected (UTC)");

                    b.Property<string>("DetectionRule")
                        .HasColumnType("jsonb")
                        .HasComment("Detection rule that triggered alert (JSON)");

                    b.Property<decimal?>("DeviationPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasComment("Deviation percentage from baseline");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Device information");

                    b.Property<string>("EmailRecipients")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Email recipients (comma-separated)");

                    b.Property<bool>("EmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether email notification was sent");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Email sent timestamp");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Escalation timestamp");

                    b.Property<string>("EscalatedTo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Escalated to (email or system)");

                    b.Property<string>("Geolocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Geolocation information");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasComment("IP address associated with alert");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag");

                    b.Property<string>("RecommendedActions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Recommended actions to address the alert");

                    b.Property<bool>("RequiresEscalation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether alert requires escalation");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Resolution notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When alert was resolved (UTC)");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasComment("User ID who resolved the alert");

                    b.Property<string>("ResolvedByEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Email of user who resolved");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasComment("Risk score 0-100 calculated by anomaly detection");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasComment("Alert severity level (CRITICAL, EMERGENCY, HIGH, MEDIUM, LOW)");

                    b.Property<bool>("SiemSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether SIEM notification was sent");

                    b.Property<DateTime?>("SiemSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("SIEM sent timestamp");

                    b.Property<string>("SiemSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("SIEM system name");

                    b.Property<string>("SlackChannels")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Slack channels notified");

                    b.Property<bool>("SlackSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether Slack notification was sent");

                    b.Property<DateTime?>("SlackSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Slack sent timestamp");

                    b.Property<string>("SmsRecipients")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("SMS recipients (comma-separated)");

                    b.Property<bool>("SmsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether SMS notification was sent");

                    b.Property<DateTime?>("SmsSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("SMS sent timestamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Alert status (NEW, ACKNOWLEDGED, IN_PROGRESS, RESOLVED, etc.)");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Tags for categorization");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasComment("Tenant ID (null for platform-level alerts)");

                    b.Property<string>("TenantName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Tenant name for reporting");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Alert title/summary");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("User agent string");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("User email address");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("User full name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("User ID who triggered the alert");

                    b.Property<string>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("User role at time of alert");

                    b.HasKey("Id");

                    b.HasIndex("AlertType")
                        .HasDatabaseName("IX_SecurityAlerts_AlertType");

                    b.HasIndex("AuditLogId")
                        .HasDatabaseName("IX_SecurityAlerts_AuditLogId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_SecurityAlerts_CreatedAt");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_SecurityAlerts_Severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SecurityAlerts_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SecurityAlerts_TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SecurityAlerts_UserId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_SecurityAlerts_Status_CreatedAt");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_SecurityAlerts_TenantId_CreatedAt");

                    b.HasIndex("Severity", "Status", "CreatedAt")
                        .HasDatabaseName("IX_SecurityAlerts_Severity_Status_CreatedAt");

                    b.ToTable("SecurityAlerts", "master", t =>
                        {
                            t.HasComment("Production-grade security alert system for real-time threat detection. Supports SOX, GDPR, ISO 27001, PCI-DSS compliance. Integrates with Email, SMS, Slack, and SIEM systems.");
                        });
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.SubscriptionNotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DaysUntilExpiryAtNotification")
                        .HasColumnType("integer")
                        .HasComment("Days until expiry at time of notification (audit trail)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Error message if delivery failed");

                    b.Property<bool>("DeliverySuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether email was delivered successfully");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Email subject line");

                    b.Property<DateTime?>("FollowUpCompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When follow-up action was completed");

                    b.Property<string>("FollowUpNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Notes about follow-up action taken");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer")
                        .HasComment("Type of notification sent (30d, 15d, 7d, expiry, etc.)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Recipient email address (audit trail)");

                    b.Property<bool>("RequiresFollowUp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Does this notification require follow-up action?");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date/time when notification was sent (UTC)");

                    b.Property<DateTime>("SubscriptionEndDateAtNotification")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Subscription end date at time of notification (audit trail)");

                    b.Property<Guid?>("SubscriptionPaymentId")
                        .HasColumnType("uuid")
                        .HasComment("Related subscription payment ID (if applicable)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to Tenant");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NotificationType")
                        .HasDatabaseName("IX_SubscriptionNotificationLogs_NotificationType");

                    b.HasIndex("SentDate")
                        .HasDatabaseName("IX_SubscriptionNotificationLogs_SentDate");

                    b.HasIndex("SubscriptionPaymentId")
                        .HasDatabaseName("IX_SubscriptionNotificationLogs_SubscriptionPaymentId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SubscriptionNotificationLogs_TenantId");

                    b.HasIndex("RequiresFollowUp", "FollowUpCompletedDate")
                        .HasDatabaseName("IX_SubscriptionNotificationLogs_RequiresFollowUp");

                    b.HasIndex("TenantId", "SentDate")
                        .HasDatabaseName("IX_SubscriptionNotificationLogs_TenantId_SentDate");

                    b.HasIndex("TenantId", "NotificationType", "SentDate")
                        .HasDatabaseName("IX_SubscriptionNotificationLogs_TenantId_Type_SentDate");

                    b.ToTable("SubscriptionNotificationLogs", "master", t =>
                        {
                            t.HasComment("Production-grade subscription notification audit log. Prevents duplicate email sends (Stripe, Chargebee pattern). IMMUTABLE - logs are historical records for compliance. Indexed on TenantId, NotificationType, SentDate for fast duplicate checks.");
                        });
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.SubscriptionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountMUR")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Amount in Mauritian Rupees (MUR) - decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Payment due date for grace period calculations");

                    b.Property<int>("EmployeeTier")
                        .HasColumnType("integer")
                        .HasComment("Employee tier at time of payment (audit trail)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxExempt")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Additional notes about the payment");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date when payment was marked as paid");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Payment method (Bank Transfer, Cash, Cheque, etc.)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Invoice, receipt, or bank transaction reference");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Subscription period end date (usually +365 days)");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Subscription period start date");

                    b.Property<string>("ProcessedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("SuperAdmin who confirmed the payment (audit trail)");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("Payment status (Pending, Paid, Overdue, Failed, etc.)");

                    b.Property<decimal>("SubtotalMUR")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmountMUR")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to Tenant");

                    b.Property<decimal>("TotalMUR")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_SubscriptionPayments_DueDate");

                    b.HasIndex("PaidDate")
                        .HasDatabaseName("IX_SubscriptionPayments_PaidDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SubscriptionPayments_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SubscriptionPayments_TenantId");

                    b.HasIndex("TenantId", "PeriodStartDate")
                        .HasDatabaseName("IX_SubscriptionPayments_TenantId_PeriodStartDate");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_SubscriptionPayments_TenantId_Status");

                    b.ToTable("SubscriptionPayments", "master", t =>
                        {
                            t.HasComment("Production-grade yearly subscription payment history. IMMUTABLE - payments are historical records. Manual payment processing by SuperAdmin with full audit trail. Indexed on TenantId, PaymentDate, Status for fast queries.");
                        });
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActivationTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AdminFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ApiCallsPerMonth")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CurrentStorageGB")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentUserCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeTier")
                        .HasColumnType("integer");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GracePeriodStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Grace period start date (when subscription expired)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGovernmentEntity")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastNotificationSent")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Last subscription notification sent (timestamp)");

                    b.Property<int?>("LastNotificationType")
                        .HasColumnType("integer")
                        .HasComment("Type of last notification sent (prevents duplicates)");

                    b.Property<int>("MaxStorageGB")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SectorSelectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SoftDeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SuspensionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SuspensionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("YearlyPriceMUR")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Yearly subscription price in Mauritian Rupees (MUR)");

                    b.HasKey("Id");

                    b.HasIndex("ContactEmail");

                    b.HasIndex("SchemaName")
                        .IsUnique();

                    b.HasIndex("SectorId");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.HasIndex("SubscriptionEndDate")
                        .HasDatabaseName("IX_Tenants_SubscriptionEndDate");

                    b.HasIndex("Status", "SubscriptionEndDate")
                        .HasDatabaseName("IX_Tenants_Status_SubscriptionEndDate");

                    b.ToTable("Tenants", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.Village", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<string>("LocalityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VillageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("VillageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VillageNameFrench")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("DistrictId");

                    b.HasIndex("PostalCode");

                    b.HasIndex("VillageCode")
                        .IsUnique();

                    b.ToTable("Villages", "master");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.ActivationResendLog", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.FeatureFlag", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.IndustrySector", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.IndustrySector", "ParentSector")
                        .WithMany("SubSectors")
                        .HasForeignKey("ParentSectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentSector");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.PostalCode", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS.Core.Entities.Master.Village", "Village")
                        .WithMany()
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Village");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.RefreshToken", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.SectorComplianceRule", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.IndustrySector", "Sector")
                        .WithMany("ComplianceRules")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.SubscriptionNotificationLog", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.SubscriptionPayment", "SubscriptionPayment")
                        .WithMany()
                        .HasForeignKey("SubscriptionPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRMS.Core.Entities.Master.Tenant", "Tenant")
                        .WithMany("SubscriptionNotificationLogs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscriptionPayment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.SubscriptionPayment", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.Tenant", "Tenant")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.Tenant", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.IndustrySector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.Village", b =>
                {
                    b.HasOne("HRMS.Core.Entities.Master.District", "District")
                        .WithMany("Villages")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.District", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.IndustrySector", b =>
                {
                    b.Navigation("ComplianceRules");

                    b.Navigation("SubSectors");
                });

            modelBuilder.Entity("HRMS.Core.Entities.Master.Tenant", b =>
                {
                    b.Navigation("SubscriptionNotificationLogs");

                    b.Navigation("SubscriptionPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
